services:
  - type: web
    name: taskmanager-cba
    runtime: docker
    plan: free
    region: singapore
    branch: master
    rootDir: .
    dockerfilePath: ./TaskManager.Web/Dockerfile
    healthCheckPath: "/"
